### PR TITLE
Small Patch

### PR DESCRIPTION
**Pull request by felixdivo**
This PR:

- Adds a `.gitignore` file as in the GitHub templates ([github/gitignore](https://github.com/github/gitignore))
- Adds a `setup.py` and moves the file into a subfolder to be able to run `pip install -e .` to install the package locally. Adds that information to the REAMDE.
- Updates the `README.md` to run again
- Fix documentation on renamed parameters
- Orders imports, makes them relative and cleans them up to only include used ones

If any change is not wanted, just say so and I'll remove it. The example code from the README is btw. duplicated in `einet.py` (at the bottom of the file). I guess one could remove it from there or also apply the patch to that part.

### CODE REVIEW

**Comment by felixdivo** [comment]
CC @steven-lang

**Comment by felixdivo** [comment]
If the changes are still wanted, I can offer to resolve the conflicts.

**Comment by steven-lang** [comment]
Absolutely - the PR is great, I just didn't have the time to resolve and merge it yet. I will probably find time on Friday, but if you want to, feel free to resolve the conflicts and I'm happy to merge it afterward.

**Comment by felixdivo** [comment]
I'll have a look later this day

**Comment by felixdivo** [comment]
@steven-lang should be done

**Comment by felixdivo** [comment]
I tested that `examples/test_iris.py` still runs.

**Pull request merged**
